SRC_DIR = "src"
WORK_DIR = "work"
LIB_DIR = "lib"
dataset_version = "GeoCSV 2.0"
delimiter = "|"
na_rep = "nan"
extension = {"geocsv": ".csv", "netcdf": ".nc"}
line_break = "\n"
cmap = "jet_r"
interpolation_method = ["linear", "nearest"]
